version: '3.8'

volumes:
  app_pg_data:
    name: app_pg_data

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - APP_ALLOWED_HOSTS=["*"]
      - APP_DATABASES__default__ENGINE=django.db.backends.postgresql
      - APP_DATABASES__default__NAME=app
      - APP_DATABASES__default__USER=app
      - APP_DATABASES__default__PASSWORD=app
      - APP_DATABASES__default__HOST=postgres
      - DJANGO_SETTINGS_MODULE=core.settings
  
  postgres:
    image: "postgres:12"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    volumes:
      - "app_pg_data:/var/lib/postgresql/data"