# Generated by Django 4.2.6 on 2023-10-12 17:22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(
                    auto_created=True, auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),  # NOQA
                ('first_name', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(
                    blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,  # NOQA
                 parent_link=True, primary_key=True, serialize=False, to='person.person')),  # NOQA
                ('grade', models.CharField(blank=True, max_length=50, null=True)),  # NOQA
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,  # NOQA
                 related_name='students_school', to='schools.school')),
            ],
            options={
                'abstract': False,
            },
            bases=('person.person',),
        ),
    ]
